---
- hosts: powervc17
  gather_facts: false
  user: root
  tasks:

  - name: creating user / changing password
    user:
      state: present
      name: "{{ demowas_user }}"
      groups: powervc-filter
      #generate_ssh_key: yes
      #ssh_key_bits: 1024
      #ssh_key_file: .ssh/id_rsa
      password: "{{ 'ansiblewas' | password_hash('sha512') }}"

- hosts: localhost
  gather_facts: true 
  #user: steph
  vars:
    roles_list: 
      - vm_user
      - deployer
      - self_service
      - image_manager
      - storage_manager
      - vm_manager

  tasks:
          #- name: Authenticate to the cloud and retrieve the service catalog
    #os_auth:
    #cloud: powervc17
    #- os_project_info:
    #cloud: powervc17
    #name: demo_ansible_was
    #register: result
    #- debug:
    #msg: "{{ result.openstack_projects }}"
      
  - name: assigin  role to project
    os_user_role:
      cloud: powervc17
      user: "{{demowas_user}}"
      role:  "{{item}}" 
      project: demo_ansible_was
      state: present
    loop: "{{ roles_list }}"


  
- hosts: control
  gather_facts: false
  user: root
  #vars:
  #user_name_for_list: was
  #number_of_users: 2
  tasks:


  - name: creating groupd
    group: 
      name: demowas_user
  - name: creating user / changing password
    user:
      state: present
      name: "{{ demowas_user }}"
      groups: demowas_user
      generate_ssh_key: yes
      ssh_key_bits: 1024
      ssh_key_file: .ssh/id_rsa
      password: "{{ 'ansiblewas' | password_hash('sha512') }}"

