---
- hosts: localhost
  gather_facts: true 
  vars:
    roles_list:
      - vm_user         
      - deployer        
      - image_manager   
      - storage_manager 
      - vm_manager      
      - self_service      

  tasks:

  - name: listing all VMs
    os_server_info:
      cloud: devstack
      #filters:
      #  vm_state: active
    register: vm
    tags: deletevm


  - debug:
      msg: "{{ vm | json_query('openstack_servers[*].{name: name}')  }}"
    tags: deletevm

  - name: showing disks to delete
    debug:
      msg: "{{ vm | json_query('openstack_servers[*].{name: name, volumes: volumes} ')  }}"
    tags: deletevm

  - meta: end_play 

  - name: removing role from  project
    os_user_role:
      state: absent
      cloud: devstack
      user: "{{ demowas_user }}"
      role: "{{ item }}"
      project: snproject 
    loop: "{{ roles_list }}"


- hosts: powervc17
  gather_facts: false
  user: root
  tasks:
  - meta: end_play

  - name: deleting user
    user:
      state: absent 
      name: "{{ demowas_user }}"
      force: yes 
  - name: deleting home directory for user "{{ demowas_user }}"
    file: 
      path: "/home/{{ demowas_user }}"
      state: absent
  
- hosts: control
  gather_facts: false
  user: root
  tasks:
  - meta: end_play

  - name: deleting 
    user:
      state: absent 
      name: "{{ demowas_user }}"
      force: yes 
  - name: deleting home directory for user "{{ demowas_user }}"
    file: 
      path: "/home/{{ demowas_user }}"
      state: absent
