---
  - name: getting ID
    shell: id

  - name: running ls
    shell: ls


  - name: Setting password for ansiblewasuser
    script: 
      cmd: "files/chansiblewas_password.sh ansible {{ user_password }}"


  
